# Generated by Django 4.1.10 on 2023-07-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_fram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fram',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
